# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmhYAuWO7pfv8IITQxXKNVSkwpZZNP4E
"""

!pip install ultralytics

!unzip full_cable.zip -d full_cable

!find full_cable -type d | head -50

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="full_cable/data.yaml",
    epochs=130,
    imgsz=320,
    batch=16,
    patience=20,
    device=0,
    augment=True
)

model.val()

model.predict(source="full_cable/valid/images", save=True)

from ultralytics import YOLO

model = YOLO("runs/detect/train/weights/best.pt")

metrics = model.val()

!zip -r model_results.zip /content/runs/detect/train
from google.colab import files
files.download("model_results.zip")

from google.colab import files

files.download("/content/runs/detect/train/weights/best.pt")

model.val(data="full_cable/data.yaml", split="test")

from ultralytics import YOLO

model = YOLO("runs/detect/train/weights/best.pt")

model.export(
    format="onnx",
    imgsz=320,
    simplify=True,
    opset=12
)

!ls runs/detect/train/weights

from google.colab import files
files.download("runs/detect/train/weights/best.onnx")

!ls /content/runs/detect/train/weights

from google.colab import files

files.download("/content/runs/detect/train/weights/best.onnx")
files.download("full_cable/data.yaml")

# Add the Raspberry Pi apt repo to Colab's Linux environment
!wget -qO- https://archive.raspberrypi.com/debian/raspberrypi.gpg.key | gpg --dearmor > /tmp/rpi.gpg
!sudo mv /tmp/rpi.gpg /usr/share/keyrings/raspberrypi-archive-keyring.gpg
!echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] https://archive.raspberrypi.com/debian/ bookworm main" | sudo tee /etc/apt/sources.list.d/raspi.list
!sudo apt update
!sudo apt install imx500-all -y

!sudo apt-get install -y python3-libcamera python3-kms++
!pip install numpy onnx onnxruntime

from ultralytics import YOLO

model = YOLO("best.pt")
model.export(format="imx500", imgsz=320)

from google.colab import files
files.download("/content/best_imx_model/packerOut.zip")

from google.colab import files
files.download("/content/best_imx_model/labels.txt")