# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmhYAuWO7pfv8IITQxXKNVSkwpZZNP4E
"""

# ── 1. INSTALL DEPENDENCIES ───────────────────────────────────────────────────

# Install the Ultralytics library, which provides the YOLOv8 implementation
!pip install ultralytics


# ── 2. PREPARE DATASET ────────────────────────────────────────────────────────

# Unzip the dataset archive into a folder called 'full_cable'
!unzip full_cable.zip -d full_cable

# Preview the extracted directory structure (shows up to 50 directories)
!find full_cable -type d | head -50


# ── 3. TRAIN THE MODEL ────────────────────────────────────────────────────────

from ultralytics import YOLO

# Load a pretrained YOLOv8 nano model as the starting point for transfer learning
model = YOLO("yolov8n.pt")

# Train the model on the cable dataset
model.train(
    data="full_cable/data.yaml",  # Path to dataset config (class names, train/val/test splits)
    epochs=130,                   # Maximum number of training epochs
    imgsz=320,                    # Resize all images to 320×320 pixels
    batch=16,                     # Number of images processed per training step
    patience=20,                  # Stop early if no improvement after 20 epochs
    device=0,                     # Use GPU 0 for training
    augment=True                  # Apply built-in data augmentation (flips, mosaic, etc.)
)

# Evaluate the model on the validation set after training
model.val()

# Run inference on validation images and save the annotated results to disk
model.predict(source="full_cable/valid/images", save=True)


# ── 4. EVALUATE THE BEST CHECKPOINT ──────────────────────────────────────────

from ultralytics import YOLO

# Reload the best weights saved during training
model = YOLO("runs/detect/train/weights/best.pt")

# Run validation and capture metrics (mAP, precision, recall, etc.)
metrics = model.val()


# ── 5. DOWNLOAD TRAINING RESULTS ─────────────────────────────────────────────

# Zip the entire training output folder (weights, plots, metrics)
!zip -r model_results.zip /content/runs/detect/train

from google.colab import files

# Download the zipped results archive to the local machine
files.download("model_results.zip")

# Also download just the best model weights file on its own
files.download("/content/runs/detect/train/weights/best.pt")


# ── 6. EVALUATE ON THE TEST SPLIT ────────────────────────────────────────────

# Run a separate validation pass using the held-out test split
model.val(data="full_cable/data.yaml", split="test")


# ── 7. EXPORT TO ONNX FORMAT ─────────────────────────────────────────────────

from ultralytics import YOLO

# Reload the best weights ready for export
model = YOLO("runs/detect/train/weights/best.pt")

# Export the model to ONNX — a portable, framework-agnostic format
model.export(
    format="onnx",    # Target format
    imgsz=320,        # Must match the image size used during training
    simplify=True,    # Apply ONNX simplification to reduce graph complexity
    opset=12          # ONNX opset version (12 has broad runtime support)
)

# Verify the exported weights are present
!ls runs/detect/train/weights

from google.colab import files

# Download the ONNX model
files.download("runs/detect/train/weights/best.onnx")

# Double-check the weights directory and re-download both the ONNX model and
# the dataset YAML (needed for class names at inference time)
!ls /content/runs/detect/train/weights

files.download("/content/runs/detect/train/weights/best.onnx")
files.download("full_cable/data.yaml")


# ── 8. EXPORT FOR SONY IMX500 (RASPBERRY PI AI CAMERA) ───────────────────────

# The IMX500 is an AI-capable image sensor used on the Raspberry Pi AI Camera.
# This section converts the model into the proprietary packed format the sensor requires.

# Add the Raspberry Pi apt repository so we can install IMX500 tooling
!wget -qO- https://archive.raspberrypi.com/debian/raspberrypi.gpg.key | gpg --dearmor > /tmp/rpi.gpg
!sudo mv /tmp/rpi.gpg /usr/share/keyrings/raspberrypi-archive-keyring.gpg
!echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] https://archive.raspberrypi.com/debian/ bookworm main" | sudo tee /etc/apt/sources.list.d/raspi.list
!sudo apt update

# Install the IMX500 model packaging tools
!sudo apt install imx500-all -y

# Install additional Python dependencies required for the IMX500 export pipeline
!sudo apt-get install -y python3-libcamera python3-kms++
!pip install numpy onnx onnxruntime

from ultralytics import YOLO

# Reload the best weights one final time for the IMX500 export
model = YOLO("best.pt")

# Convert and pack the model into the IMX500 format at 320×320 resolution
model.export(format="imx500", imgsz=320)

from google.colab import files

# Download the packed IMX500 model archive (deploy this to the Raspberry Pi)
files.download("/content/best_imx_model/packerOut.zip")

# Download the labels file (maps class indices to human-readable names)
files.download("/content/best_imx_model/labels.txt")
